
services:
  dagster_pipeline:
    build: .
    container_name: eskom_observability_pipeline
    ports:
      - "3000:3000"
    volumes:
      # Mount local folder into the container so DuckDB data persists on machine
      - .:/app
    environment:
      - DAGSTER_HOME=/opt/dagster/dagster_home